server {
    listen 3002;
    server_name _;

    location /api {
        client_max_body_size 100M;
        proxy_pass https://api.space-21.ru;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}